export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProfilesLayout({ children, users }) {
  console.log(users)
  return (
    <div>
        {children}
    </div>
  );
}
